UNK_LABEL = "<unk>"
UNK_IDX = 0
PADDING_LABEL = "<pad>"
PADDING_IDX = 1

VOCAB_START_IDX = 2

CUTOFF = 50
TRIGGER_GOLDEN_COMPENSATION = 12
ARGUMENT_GOLDEN_COMPENSATION = 27
MAX_SUB = 10000

O_LABEL = None
ROLE_O_LABEL = None
